### ISSUE TITLE
regadm page has some issues

### ISSUE THREAD

**Issue by vismitap** [Harshita248/Scrum-Management#73]
**Describe the bug**
----
- A clear and concise description of what the bug is.
1) The header is not rendered properly
![image](https://user-images.githubusercontent.com/47056243/106686501-63737700-65f0-11eb-8535-97661131d834.png)
2) The animations also seem to have a bug
![image](https://user-images.githubusercontent.com/47056243/106686544-7ede8200-65f0-11eb-916a-35d974fb0ae3.png)
![image](https://user-images.githubusercontent.com/47056243/106687624-80a94500-65f2-11eb-8eed-704bb13b09f9.png)
3) The mobile view does not have a signup button and hence the animations cannot be triggered.
[refer this](https://imgur.com/440SkpU)

**To Reproduce**
----
- Steps to reproduce the behavior:
  1. Go to 'http://localhost:3000/regadm'
  2. Click on 'signup' button
  3. See error

**Expected behavior**
-----
- A clean register as admin page should be visible

**Possible solution**
----
- The animation and div positions need to be taken care of.

I would like to try to resolve this issue as a part of SWOC! Please assign me this issue!

**Comment by Harshita248** [comment]
Okay go ahead @vismitap

**Comment by imsachinsingh10** [comment]
Sorry, It occured while merging the files... If you want @vismitap i will correct it

**Comment by vismitap** [comment]
I was going through the files and there is lot of code commented (in css and ejs), diff css for the same tags (body tag) etc. It is taking quite a while to resolve everything. I am okay if you want to try resolving this @imsachinsingh10 . Please keep me updated so that I can move to other issues and try them. If any help needed we can collaborate too.

**Comment by Harshita248** [comment]
Done

**Comment by vismitap** [comment]
Hey! @Harshita248 The issue still persists! 
1) Refer [this link](https://imgur.com/a/mG3R3Y6). Here, you can see there are errors in register.css file from the master branch of your repository.
2) There is a lot of code commented which may not be useful and is creating confusion. 
![image](https://user-images.githubusercontent.com/47056243/107003406-bbf27200-67b2-11eb-8ad8-a0b4684f4ca9.png)
3) There are some ejs files like fetch_details.ejs, LoginForm.ejs etc where some deprecated tags are used.
4) Here, Bootstrap syntax is used in the file but the bootstrap link itself is commented. 
![image](https://user-images.githubusercontent.com/47056243/107003601-1095ed00-67b3-11eb-9b5b-b32eb98060c7.png)
5) The view of the register admin page looks still the same.

A lot of code clean-up is required! Should I go ahead and try to solve as much as I can? @Harshita248 , Should I open a new issue? Cannot move forward with the other issue you assigned.

**Comment by Harshita248** [comment]
Go ahead under this issue

**Comment by vismitap** [comment]
> Go ahead under this issue

okay! 👍

**Comment by vismitap** [comment]
Raised a PR! Please check #75
